import React from "react";
import Head from "next/head";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main>{children}</main>
      <footer></footer>
    </>
  );
}

export default Layout;
